name: build
on: [push]
jobs:
  compile-databases:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "18.x"
      - run: "TZ='Etc/Utc'; export TZ"
      - run: node workflow
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          REPO: aboutdavid/0shade
          BRANCH: main
          EMAIL: 62346025+aboutdavid@users.noreply.github.com
          NAME: aboutdavid
